apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: nyasa/boardgame
          imagePullPolicy: Always
          ports:
            - containerPort: 8080   # internal app port

---
apiVersion: v1
kind: Service
metadata:
  name: boardgame-svc
spec:
  selector:
    app: boardgame
  type: NodePort
  ports:
    - protocol: TCP
      port: 8082        # external port accessible from host
      targetPort: 8080  # maps to container port
      nodePort: 30082
